# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Retro Meter
version: "1.2.0"
slug: retrometer
description: Retro Meter add-on
url: "https://github.com/dominik-widmann/retroMeter-addon"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
#image: "ghcr.io/home-assistant/{arch}-addon-example"
privileged:
  - SYS_ADMIN
devices:
  - /dev/i2c-1
device_tree: true
startup: services
log_level: info
options:
  mqttuser: null
  mqttpasswd: null
schema:
  mqttuser: str
  mqttpasswd: password
