# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Retro Meter
version: "1.6.1"
slug: retrometer
description: Retro Meter add-on
url: "https://github.com/dominik-widmann/retroMeter-addon"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
image: "ghcr.io/dominik-widmann/{arch}-retrometer-addon"
privileged:
  - SYS_ADMIN
devices:
  - /dev/i2c-1
startup: services
options:
  mqttuser: null
  mqttpasswd: null
  mqtttopic: "meter/gas_volume"
  m3pertick: null
schema:
  mqttuser: str
  mqttpasswd: password
  mqtttopic: str
  m3pertick: float
